### ISSUE TITLE
At the "Deploy contract:" in the README, the command throws this error

### ISSUE THREAD

**Issue by devonwesley** [omisego/plasma-cash#70]
<img width="1670" alt="screen shot 2018-07-13 at 7 18 09 pm" src="https://user-images.githubusercontent.com/8162708/42704850-bbd5a3ce-86d1-11e8-90ed-4f1578028616.png">

## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
- When running `python deployment.py` I get the error pictured above. I haven't looked heavily into the contract and what the `types` are suppose to be, but its in the `RPL.sol` file.

## Expected Behavior
I was following the readme, so I expected the root_chain to deploy.

## Steps to Reproduce

1. Follow readme steps
2. Then run `python deployment.py`

## Motivation for Change
I would just like help so I can continue.

## System Specs

- python version: `3.6.6`
- pyetherem version: `none`
- environment (output of running `pip freeze`):
```
asn1crypto==0.24.0
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
behave==1.2.6
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==8.0.0
cytoolz==0.9.0.1
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
ethereum==2.3.1
flake8==3.5.0
Flask==1.0.2
future==0.16.0
hexbytes==0.1.0
idna==2.6
isort==4.3.4
itsdangerous==0.24
Jinja2==2.10
json-rpc==1.10.8
lru-dict==1.1.6
MarkupSafe==1.0
mccabe==0.6.1
mockito==1.0.12
more-itertools==4.2.0
parse==1.8.4
parse-type==0.4.2
parsimonious==0.8.0
pbkdf2==1.3
plasma==0.0.0
pluggy==0.6.0
plyvel==1.0.4
py==1.5.4
py-ecc==1.4.3
py-solc==2.1.0
pycodestyle==2.3.1
pycparser==2.18
pycryptodome==3.6.4
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.5.0
PyYAML==4.2b4
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.22
web3==4.2.0
websockets==4.0.1
Werkzeug==0.14.1
```
- operating system: `MacOS High Sierra`

Thanks in advance.

**Comment by boolafish** [comment]
@devonwesley Thanks for the reporting. Can we have your solc version as well?

**Comment by devonwesley** [comment]
`Version: 0.4.25-develop.2018.6.8+commit.ddd256a6.Darwin.appleclang` @boolafish

**Comment by boolafish** [comment]
can you downgrade to Solidity 0.4.24 for now? We have tests using 0.4.24 so that version should be more stable for our contact code.

**Comment by devonwesley** [comment]
Okay ill give that a shot.

**Comment by devonwesley** [comment]
@boolafish Solidity version `0.4.24` worked. Thank you.

**Comment by bun919tw** [comment]
Issue solved, close this.
