### ISSUE TITLE
Wait for transaction is mined before creating block in plasma chain

### ISSUE THREAD

**Issue by ldmtam** [omisego/plasma-cash#83]
```
def submit_block(self, sig):
        signature = bytes.fromhex(sig)
        if (signature == b'\x00' * 65 or
           get_sender(self.current_block.hash, signature) != self.authority):
            raise InvalidBlockSignatureException('failed to submit a block')

        merkle_hash = self.current_block.merklize_transaction_set()

        authority_address = w3.toChecksumAddress('0x' + self.authority.hex())
        self.root_chain.functions.submitBlock(merkle_hash, self.current_block_number).transact(
            {'from': authority_address}
        )

        emit('chain.block', self.current_block_number)
        self.db.save_block(self.current_block, self.current_block_number)
        self.current_block_number = self.db.increment_current_block_num()
        self.current_block = Block()

        return merkle_hash
```
In this function, I think we should wait until the block that contains our transaction is mined on Ethereum blockchain before adding new block in the plasma chain. Because of some unforseen reasons, the transaction might fail and that block in plasma chain will become invalid.

**Comment by boolafish** [comment]
Thanks for pointing this out.
Hmmm, but I think the block generating speed in child chain should usually be faster than in root chain. In a more general scenario child chain might submit multiple blocks in one root chain block. If we do it your proposed way, the child chain block generation time would be bounded by root chain.

I am actually thinking for a more general re-org protection solution. Probably operator needs to keep track with what ever latest child chain block is valid in root chain, and always tries to submit the remaining blocks. So even if re-org happens, operator will track the latest valid child chain block number, and can still publish the blocks to root chain.

**Comment by ldmtam** [comment]
I understand your point. But in my opinion, it's a little bit risky because the exit mechanism depends on the block root hash on main chain smart contract. For example, A has 10 tokens, B has 0 token, A send B 5 tokens and that transaction is included in block 10 but for some reasons, block 10 root hash is not submitted on main chain and then A is able to exit the plasma chain with 10 tokens because B doesn't have any proof to challenge. Please review my example and give me feedback.

**Comment by boolafish** [comment]
I think I am strongly influenced by the discussion here: https://github.com/omisego/research/issues/29. That's what's kind of in my mind.

As for your case, I would prefer to leave this to the user. Let say A and B is having a trade. A should give B 10 token and B provide A some goods. B can always choose to protect him/herself by waiting root chain confirmation before providing the goods. However, if it is just some small value daily life trading, B can just trust things should go smoothly, with some potential but probably pretty low risk.

How do you think?

**Comment by ldmtam** [comment]
I don't think that we should assume the value exchanging between 2 entities in plasma chain is small enough that users will accept their loss, maybe I can use plasma chain to exchange assets such as: house, land, or an kitty etc ... which is worth millions of USD. Actually, I don't have any solution for this problem =)) , but I think we should know about it and add more constraints on validator of plasma chain, make sure him/her submit the root hash later on when they failed to submit the root hash at the first time.

**Comment by boolafish** [comment]
Sorry for a late reply.

What I mean is that if they are trading large value assets, the receiver of plasma coin might want to hold until confirmed from root chain (and actually probably multiple confirmation in root chain) before he/she actually give his/her goods. The user has the flexibility to hold on their action to protect themselves.

**Comment by ldmtam** [comment]
Yes, you're right. Maybe we should leave this to users or improve UI/UX that notifies users about the amount of value in their trading so they can decide to wait for the root hash on main chain or not.
