### ISSUE TITLE
example in README not working

### ISSUE THREAD

**Issue by vascoosx** [omisego/plasma-cash#97]
I am trying to run the example in README but I got an error:

```
plasma_cash.child_chain.exceptions.PreviousTxNotFoundException: failed to apply transaction
``` 

when I tried to run 
```
userA.send_transaction(1, 1693390459388381052156419331572168595237271043726428428352746834777341368960, 10, '0x08d92dca9038ea9433254996a2d4f08d43be8227')
```

**Comment by vascoosx** [comment]
It works when I don't run `python -m plasma_cash.operator_cron_job`

**Comment by boolafish** [comment]
Sorry for that, apparently our README is not clear enough on that.
Yes, currently we are not prepared to run that command yet as it would be hard to know where the previous block is.
